name: unifiedpush_android
description: Android implementation of UnifiedPush plugin.
version: 2.2.3
homepage: "https://unifiedpush.org/developers/flutter"
documentation: "https://unifiedpush.org/developers/flutter"
repository: https://github.com/UnifiedPush/flutter-connector/tree/main/unifiedpush_android

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  unifiedpush_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  dependency_validator: ^3.0.0

flutter:
  plugin:
    implements: unifiedpush
    platforms:
      android:
        package: org.unifiedpush.flutter.connector
        pluginClass: Plugin
        dartPluginClass: UnifiedPushAndroid

#todev#dependency_overrides:
#todev#  unifiedpush_platform_interface:
#todev#    path: ../unifiedpush_platform_interface
